apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-model-pvc
  namespace: ollama
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 10Gi
