apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-data-pvc
  namespace: ollama
spec:
  storageClassName: nfs-csi-openwebui
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi