apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama-sa
  namespace: ollama
  labels:
    app: ollama
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-webui-sa
  namespace: ollama
  labels:
    app: open-webui